### ISSUE TITLE
Firefox search box text doesn't show on index page

### ISSUE THREAD

**Issue by wilyboy** [CodeForPhilly/neargreen#21]
Both the default text and text from typing into the search box do not appear when using Firefox.

**Comment by csharpie** [comment]
I did some investigation and the reason this doesn't work is due to some css in the main.css file. The class that needs to be modified is called _inputForm_. If you remove that class from the text box on the index.html page, you'll notice the text box behaves correctly, but then the text box becomes too big.

**Comment by wilyboy** [comment]
Ok cool, I should have time tomorrow to play around with that. I should have taken more notes the other day haha, I'm still trying to get down all the stuff we went over :P
